### ISSUE TITLE
undeclared identifier: 'singleItemView'

### ISSUE THREAD

**Issue by traverseda** [zielmicha/reactor.nim#19]
Using the reactor for the first time, got
    /home/traverseda/.nimble/pkgs/reactor-0.4.5/reactor/async/stream.nim(174, 34) Error: undeclared identifier: 'singleItemView'

**Comment by zielmicha** [comment]
There was a problem with version of collections.nim library, please try installing again (version 0.5.0).

**Comment by traverseda** [comment]
[deps.txt](https://github.com/zielmicha/reactor.nim/files/2111479/deps.txt)

It says it is `0.5.0`. I've included my full list of dependencies as well.

```
name: "collections"
version: "0.5.0"
author: "Micha\xC5\x82 Zieli\xC5\x84ski <michal@zielinscy.org.pl>"
desc: "Various collections and utilities"
license: "MIT"
skipDirs: "examples, doc, tests"
skipFiles: ""
skipExt: ""
installDirs: ""
installFiles: ""
installExt: ""
requires: "nim >= 0.18.0"
bin: ""
binDir: ""
srcDir: ""
backend: "c"
```

**Comment by zielmicha** [comment]
You need to have version 0.5.0 of both reactor.nim and collections.nim. You now have version 0.4.5 of reactor.nim.
