### ISSUE TITLE
asyncRaise handler/hook

### ISSUE THREAD

**Issue by JeffCarpenter** [zielmicha/reactor.nim#20]
My example use case:
Do a GET request on a server that sends the keep-alive header and closes right away. More requests intended to follow.

I could be wrong, but it seems to me that in order to prevent asyncRaise from exiting the program, what's missing is a way to override the asyncRaise handler.

**Comment by zielmicha** [comment]
asyncRaise just makes the function return fail the Future it returns. You can just check with isError (and use tryAwait, which is just a version of await that doesn't propagate the exception).

**Comment by JeffCarpenter** [comment]
Okay, thanks. I'll give that a try.
