### ISSUE TITLE
Async question

### ISSUE THREAD

**Issue by chikhpykh** [zielmicha/reactor.nim#4]
Hello, zielmicha. Please help.
What is a way in reactor to send async requests and get asynchronous responses from multiple urls?
I mean how to request few urls at once and get it's responses asynchronous.

Lib API is not so clear to understand.
Thanks

**Comment by zielmicha** [comment]
You can do something like that:
```
# you can also return something by declaring return type as Future[TYPE]
proc myrequest(): Future[void] {.async.} =
  let resp = await request(newHttpRequest("GET", "http://google.com/").get)
  # do something with response...    

proc main() {.async.} =
  # note we don't use await here
  let resp1: Future[void] = myrequest("http://google.com")
  let resp2: Future[void] = myrequest("http://amazon.com")
  # now two requests are running, await them
  await resp1
  await resp2
```
Hopefully I'll add more documentation and some examples "soon".
