### ISSUE TITLE
spawn limit

### ISSUE THREAD

**Issue by recoilme** [zielmicha/reactor.nim#8]
Hello!
We have 2500 connections on memcached server now, and i try to implement similar server.
Then i check reactor - looks like it have spawn limit on 2048 connections on my server (limits in config on server arround 500k)
Is this limitation of libuv or any hardcoded constant?
I try like this
```
import reactor/loop, reactor/async, reactor/threading, os

proc hardWork(): int =
  echo "hard work started"
  sleep(10000)
  echo "hard work finished"
  return 5

proc main() {.async.} =
  for i in 1..2500:
    let f = spawn hardWork()

main().runLoop()
```

**Comment by zielmicha** [comment]
This is most likely limitation of `threadpool` from stdlib (reactor `spawn` is a thin wrapper around it).

**Comment by zielmicha** [comment]
https://github.com/nim-lang/Nim/blob/devel/lib/pure/concurrency/threadpool.nim#L286

Anyway, you probably don't have 256-core processor, so (unless you are doing sync IO) it doesn't make sense to run more threads concurrently.

**Comment by zielmicha** [comment]
You can open issue on main Nim repo if you want `threadpool` module to support more threads. (unless you want to implement thread pool inside reactor.nim :) )
